"""dont need phone number

Revision ID: 6f0270830bba
Revises: 29c0bdc8d6d0
Create Date: 2024-01-29 15:05:19.541073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f0270830bba'
down_revision = '29c0bdc8d6d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('ingredients',
               existing_type=sa.VARCHAR(length=2048),
               type_=sa.String(length=5000),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=2048),
               type_=sa.String(length=1024),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=2048),
               existing_nullable=True)
        batch_op.alter_column('ingredients',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=2048),
               existing_nullable=True)

    # ### end Alembic commands ###
