"""better ingredients and cookbook

Revision ID: 86619cf6ed3a
Revises: f597f24bdde2
Create Date: 2024-04-25 08:54:35.993574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86619cf6ed3a'
down_revision = 'f597f24bdde2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_index('ix_ingredients_name')

    op.drop_table('ingredients')
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('instructions_list')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instructions_list', sa.VARCHAR(length=10000), nullable=True))

    op.create_table('ingredients',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('category', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.create_index('ix_ingredients_name', ['name'], unique=1)

    # ### end Alembic commands ###
