"""username to email

Revision ID: c01a8ffabf11
Revises: a21a7a25d38c
Create Date: 2024-03-07 19:11:12.478731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c01a8ffabf11'
down_revision = 'a21a7a25d38c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=128), nullable=True))
        batch_op.drop_index('ix_users_username')
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_index('ix_users_username', ['username'], unique=1)
        batch_op.drop_column('email')

    # ### end Alembic commands ###
