"""forgot password fields

Revision ID: cebd2709b8ac
Revises: d55a99a43947
Create Date: 2024-04-22 16:22:53.422154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cebd2709b8ac'
down_revision = 'd55a99a43947'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_change_password', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_change_password_expiry', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('change_password_code', sa.String(length=6), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('change_password_code')
        batch_op.drop_column('can_change_password_expiry')
        batch_op.drop_column('can_change_password')

    # ### end Alembic commands ###
